// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by generate-protos. DO NOT EDIT.

package main

import (
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/annotations"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/comments"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/extensions/base"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/extensions/ext"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/extensions/extra"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/extensions/proto3"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/fieldnames"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/import_public"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/import_public/sub"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/import_public/sub2"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/imports"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/imports/fmt"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/imports/test_a_1"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/imports/test_a_2"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/imports/test_b_1"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/issue780_oneof_conflict"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/nopackage"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/proto2"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/proto3"
	_ "xjz9600/protobuf/cmd/protoc-gen-go/testdata/retention"
)
